import { User, BODMatter, AuditLogEntry, AppNotification } from '../src/lib/types';

export const NIB_USERS: User[] = [
  {
    id: 'usr_sec_1',
    name: 'Rahel Solomon',
    email: 'rahel.solomon@nibbank.et',
    role: 'BOARD_SECRETARIAT',
    title: 'Head of Board Secretariat & Corporate Governance',
    businessArea: 'Board Secretariat',
    department: 'Office of the Board of Directors',
    phone: '+251 11 550 3288',
    avatar: 'RS',
  },
  {
    id: 'usr_ceo_1',
    name: 'Dawit Tadesse',
    email: 'dawit.tadesse@nibbank.et',
    role: 'CEO',
    title: 'Chief Executive Officer (CEO)',
    businessArea: 'Executive Management',
    department: 'Office of the CEO',
    phone: '+251 11 550 4100',
    avatar: 'DT',
  },
  {
    id: 'usr_chief_ops',
    name: 'Ephrem Bekele',
    email: 'ephrem.bekele@nibbank.et',
    role: 'CHIEF',
    title: 'Chief Operations Officer (COO)',
    businessArea: 'Banking Operations',
    department: 'Operations Division',
    phone: '+251 11 550 4210',
    avatar: 'EB',
  },
  {
    id: 'usr_chief_retail',
    name: 'Bethlehem Haile',
    email: 'bethlehem.haile@nibbank.et',
    role: 'CHIEF',
    title: 'Chief Retail & SME Banking Officer',
    businessArea: 'Retail Banking',
    department: 'Retail & SME Division',
    phone: '+251 11 550 4220',
    avatar: 'BH',
  },
  {
    id: 'usr_chief_risk',
    name: 'Michael Girma',
    email: 'michael.girma@nibbank.et',
    role: 'CHIEF',
    title: 'Chief Risk & Compliance Officer (CRO)',
    businessArea: 'Risk & Compliance',
    department: 'Risk Management Division',
    phone: '+251 11 550 4230',
    avatar: 'MG',
  },
  {
    id: 'usr_chief_it',
    name: 'Henok Samuel',
    email: 'henok.samuel@nibbank.et',
    role: 'CHIEF',
    title: 'Chief Information & Digital Officer (CIDO)',
    businessArea: 'Information Technology',
    department: 'Digital Systems Division',
    phone: '+251 11 550 4240',
    avatar: 'HS',
  },
  {
    id: 'usr_deputy_branch',
    name: 'Yonas Alemu',
    email: 'yonas.alemu@nibbank.et',
    role: 'DEPUTY_CHIEF',
    title: 'Deputy Chief - Branch Network Operations',
    businessArea: 'Banking Operations',
    department: 'Branch Support Unit',
    phone: '+251 11 550 4310',
    avatar: 'YA',
  },
  {
    id: 'usr_deputy_digital',
    name: 'Samrawit Negash',
    email: 'samrawit.negash@nibbank.et',
    role: 'DEPUTY_CHIEF',
    title: 'Deputy Chief - Digital Channels & Payments',
    businessArea: 'Information Technology',
    department: 'E-Banking & Switch Department',
    phone: '+251 11 550 4320',
    avatar: 'SN',
  },
  {
    id: 'usr_dir_branch_ops',
    name: 'Solomon Mengistu',
    email: 'solomon.mengistu@nibbank.et',
    role: 'DIRECTOR',
    title: 'Director - Branch Operations & Service Delivery',
    businessArea: 'Banking Operations',
    department: 'Branch Operations Directorate',
    phone: '+251 11 550 4410',
    avatar: 'SM',
  },
  {
    id: 'usr_dir_credit',
    name: 'Tigist Abebe',
    email: 'tigist.abebe@nibbank.et',
    role: 'DIRECTOR',
    title: 'Director - Credit Assessment & Underwriting',
    businessArea: 'Retail Banking',
    department: 'Credit Appraisal Directorate',
    phone: '+251 11 550 4420',
    avatar: 'TA',
  },
  {
    id: 'usr_dir_compliance',
    name: 'Daniel Kebede',
    email: 'daniel.kebede@nibbank.et',
    role: 'DIRECTOR',
    title: 'Director - Regulatory Compliance & AML/CFT',
    businessArea: 'Risk & Compliance',
    department: 'Compliance Directorate',
    phone: '+251 11 550 4430',
    avatar: 'DK',
  },
  {
    id: 'usr_dir_it_sec',
    name: 'Meron Tesfaye',
    email: 'meron.tesfaye@nibbank.et',
    role: 'DIRECTOR',
    title: 'Director - IT Infrastructure & Cyber Security',
    businessArea: 'Information Technology',
    department: 'IT Security Directorate',
    phone: '+251 11 550 4440',
    avatar: 'MT',
  },
  {
    id: 'usr_dir_cust_exp',
    name: 'Berhanu Kassaye',
    email: 'berhanu.kassaye@nibbank.et',
    role: 'DIRECTOR',
    title: 'Director - Customer Experience & Service Quality',
    businessArea: 'Banking Operations',
    department: 'Quality Assurance Directorate',
    phone: '+251 11 550 4450',
    avatar: 'BK',
  },
  {
    // The system administrator. Not a participant in the Board workflow — this
    // account exists to administer the directory, matter types and settings,
    // and is the account used to recover the others. Exempt from the forced
    // first-sign-in password change (see passwordChangeEnforced in lib/session).
    id: 'usr_admin_1',
    name: 'System Administrator',
    email: 'admin@nibbank.et',
    role: 'ADMIN',
    title: 'System Administrator',
    businessArea: 'Board Secretariat',
    department: 'Information Systems',
    phone: '+251 11 550 3200',
    avatar: 'SA',
  },
];

export const INITIAL_MATTERS: BODMatter[] = [
  {
    id: 'BOD-2026-001',
    resolutionNumber: 'NIB/BOD/DIR/2026/025',
    matterType: 'Directive',
    title: 'Implementation of New Branch Customer Complaint Procedure & 48-Hour Resolution Framework',
    description:
      'The Board of Directors directs executive management to institute an automated, unified customer complaint logging, tracking, and escalation mechanism across all 240+ NIB International Bank branches with mandatory SLA of 48 hours for retail disputes.',
    boardMeetingDate: '2026-07-15',
    boardDecisionDate: '2026-07-16',
    effectiveDate: '2026-08-01',
    priority: 'Urgent',
    deadline: '2026-09-30',
    businessArea: 'Banking Operations',
    
    responsibleChiefId: 'usr_chief_ops',
    responsibleChiefName: 'Ephrem Bekele',
    responsibleChiefTitle: 'Chief Operations Officer (COO)',
    
    responsibleDeputyChiefId: 'usr_deputy_branch',
    responsibleDeputyChiefName: 'Yonas Alemu',
    responsibleDeputyChiefTitle: 'Deputy Chief - Branch Network Operations',
    
    responsibleDirectorId: 'usr_dir_branch_ops',
    responsibleDirectorName: 'Solomon Mengistu',
    responsibleDirectorTitle: 'Director - Branch Operations & Service Delivery',
    
    currentOwnerId: 'usr_chief_ops',
    currentOwnerName: 'Ephrem Bekele',
    currentOwnerRole: 'CHIEF',
    currentOwnerTitle: 'Chief Operations Officer (COO)',
    
    accountableExecutiveId: 'usr_ceo_1',
    accountableExecutiveName: 'Dawit Tadesse',
    accountableExecutiveTitle: 'Chief Executive Officer (CEO)',
    
    status: 'Implementation Submitted',
    progress: 90,
    currentStage: 'Under Review / Confirmation by COO & CEO',
    daysRemaining: 44,
    isOverdue: false,
    lastAction: 'Director submitted comprehensive implementation report and branch evidence',
    lastActionDate: '2026-08-15T14:30:00Z',
    lastActionUserId: 'usr_dir_branch_ops',
    lastActionUserName: 'Solomon Mengistu',
    nextRequiredAction: 'Chief Operations Officer to review implementation evidence and approve confirmation',
    nextActionRole: 'CHIEF',
    overallStatus: 'Awaiting Chief & Executive Confirmation',
    
    documents: [
      {
        id: 'doc_101',
        name: 'BOD_Resolution_2026_025_Signed.pdf',
        category: 'ORIGINAL_BOARD_DOC',
        fileType: 'application/pdf',
        fileSize: '2.4 MB',
        uploadedBy: 'Rahel Solomon',
        uploadedByRole: 'BOARD_SECRETARIAT',
        uploadedAt: '2026-07-17T09:00:00Z',
        description: 'Official signed Board of Directors Resolution extract for Complaint Procedure',
      },
      {
        id: 'doc_102',
        name: 'Standard_Operating_Procedure_Complaint_Handling_v3.pdf',
        category: 'SUPPORTING',
        fileType: 'application/pdf',
        fileSize: '4.1 MB',
        uploadedBy: 'Solomon Mengistu',
        uploadedByRole: 'DIRECTOR',
        uploadedAt: '2026-08-15T14:20:00Z',
        description: 'Updated Branch SOP with 48h escalation tiers and SMS notification flow',
      },
      {
        id: 'doc_103',
        name: 'Branch_Staff_Training_Attendance_Log_All_Regions.xlsx',
        category: 'IMPLEMENTATION_EVIDENCE',
        fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        fileSize: '1.8 MB',
        uploadedBy: 'Solomon Mengistu',
        uploadedByRole: 'DIRECTOR',
        uploadedAt: '2026-08-15T14:25:00Z',
        description: 'Certified sign-off sheets covering 1,840 branch service officers across 4 regional clusters',
      },
    ],
    
    implementationReport: {
      id: 'rep_001',
      submittedBy: 'usr_dir_branch_ops',
      directorName: 'Solomon Mengistu',
      directorTitle: 'Director - Branch Operations & Service Delivery',
      submissionDate: '2026-08-15',
      actionTaken: 'Standard Operating Procedure (SOP) drafted, vetted by Legal & QA, deployed to Core Banking Portal and rolled out across all 240+ branches with unified ticketing IDs.',
      whatWasImplemented: '1. Automated digital ticket generation in Finacle core banking.\n2. 48-hour auto-escalation trigger to District Managers.\n3. Mandatory weekly dispute reconciliation dashboard.\n4. Comprehensive training completed for 1,840 branch staff.',
      implementationDate: '2026-08-12',
      responsibleArea: 'Branch Operations Directorate in coordination with Customer Experience',
      resultOutcome: 'Average complaint resolution turnaround time dropped from 8.4 business days to 1.9 business days. 96.2% of retail customer inquiries are now resolved within the 48-hour BOD mandate.',
      currentCondition: 'Fully operational in all City and Outlying Branches. Live dashboard monitoring enabled for District Directors.',
      remainingIssues: 'None. Continuous QA audits scheduled monthly.',
      evidenceDocuments: [],
      comments: 'Directive objectives fully satisfied ahead of the September 30 deadline. Requesting formal review and confirmation of completion.',
      completionDate: '2026-08-15',
      completionStatus: 'Completed',
    },
    
    routingPath: [
      {
        id: 'wn_1',
        level: 'BOARD_SECRETARIAT',
        label: 'Board Secretariat',
        userId: 'usr_sec_1',
        userName: 'Rahel Solomon',
        userTitle: 'Head of Board Secretariat & Corporate Governance',
        role: 'BOARD_SECRETARIAT',
        businessArea: 'Board Secretariat',
        assignedAt: '2026-07-17T09:00:00Z',
        actedAt: '2026-07-17T10:15:00Z',
        actionTaken: 'Registered BOD Directive and forwarded to CEO Secretariat',
        status: 'COMPLETED',
        comment: 'Formal BOD direction from 42nd Regular Board Session. High priority.',
      },
      {
        id: 'wn_2',
        level: 'CEO',
        label: 'Chief Executive Officer',
        userId: 'usr_ceo_1',
        userName: 'Dawit Tadesse',
        userTitle: 'Chief Executive Officer (CEO)',
        role: 'CEO',
        businessArea: 'Executive Management',
        assignedAt: '2026-07-17T10:15:00Z',
        actedAt: '2026-07-18T08:45:00Z',
        actionTaken: 'Reviewed and assigned operational responsibility to Chief Operations Officer',
        status: 'COMPLETED',
        comment: 'Please coordinate with Retail and Digital to ensure seamless cross-channel logging.',
      },
      {
        id: 'wn_3',
        level: 'CHIEF',
        label: 'Chief Operations Officer',
        userId: 'usr_chief_ops',
        userName: 'Ephrem Bekele',
        userTitle: 'Chief Operations Officer (COO)',
        role: 'CHIEF',
        businessArea: 'Banking Operations',
        assignedAt: '2026-07-18T08:45:00Z',
        actedAt: '2026-07-18T14:00:00Z',
        actionTaken: 'Assigned to Deputy Chief - Branch Network',
        status: 'COMPLETED',
        comment: 'Work closely with Director Solomon to draft revised SOP and schedule staff training.',
      },
      {
        id: 'wn_4',
        level: 'DEPUTY_CHIEF',
        label: 'Deputy Chief - Branch Network',
        userId: 'usr_deputy_branch',
        userName: 'Yonas Alemu',
        userTitle: 'Deputy Chief - Branch Network Operations',
        role: 'DEPUTY_CHIEF',
        businessArea: 'Banking Operations',
        assignedAt: '2026-07-18T14:00:00Z',
        actedAt: '2026-07-19T09:30:00Z',
        actionTaken: 'Assigned to Director - Branch Operations as Final Operational Owner',
        status: 'COMPLETED',
        comment: 'Solomon, please lead implementation, training, and assemble evidence pack.',
      },
      {
        id: 'wn_5',
        level: 'DIRECTOR',
        label: 'Director - Branch Operations',
        userId: 'usr_dir_branch_ops',
        userName: 'Solomon Mengistu',
        userTitle: 'Director - Branch Operations & Service Delivery',
        role: 'DIRECTOR',
        businessArea: 'Banking Operations',
        assignedAt: '2026-07-19T09:30:00Z',
        actedAt: '2026-08-15T14:30:00Z',
        actionTaken: 'Accepted ownership, executed branch SOP rollout, and submitted final Implementation Report',
        status: 'COMPLETED',
        comment: 'Full implementation accomplished. All evidence attached.',
      },
      {
        id: 'wn_6',
        level: 'REVIEW_CONFIRMATION',
        label: 'Review & Confirmation',
        userId: 'usr_chief_ops',
        userName: 'Ephrem Bekele',
        userTitle: 'Chief Operations Officer (COO)',
        role: 'CHIEF',
        businessArea: 'Banking Operations',
        assignedAt: '2026-08-15T14:30:00Z',
        status: 'ACTIVE',
      },
    ],
    
    clarifications: [],
    createdAt: '2026-07-17T09:00:00Z',
    createdBy: 'usr_sec_1',
    createdByName: 'Rahel Solomon',
    updatedAt: '2026-08-15T14:30:00Z',
  },
  {
    id: 'BOD-2026-002',
    resolutionNumber: 'NIB/BOD/RES/2026/031',
    matterType: 'Resolution',
    title: 'Capital Adequacy & Single Obligor Exposure Limits Enhancement for FY 2026/27',
    description:
      'The Board resolved to tighten single obligor credit exposure ceiling to 20% of total unimpaired regulatory capital and mandated quarterly stress-testing reports to be tabled to the Board Risk Committee.',
    boardMeetingDate: '2026-07-28',
    boardDecisionDate: '2026-07-29',
    effectiveDate: '2026-08-15',
    priority: 'High',
    deadline: '2026-10-15',
    businessArea: 'Risk & Compliance',
    
    responsibleChiefId: 'usr_chief_risk',
    responsibleChiefName: 'Michael Girma',
    responsibleChiefTitle: 'Chief Risk & Compliance Officer (CRO)',
    
    responsibleDirectorId: 'usr_dir_compliance',
    responsibleDirectorName: 'Daniel Kebede',
    responsibleDirectorTitle: 'Director - Regulatory Compliance & AML/CFT',
    
    currentOwnerId: 'usr_dir_compliance',
    currentOwnerName: 'Daniel Kebede',
    currentOwnerRole: 'DIRECTOR',
    currentOwnerTitle: 'Director - Regulatory Compliance & AML/CFT',
    
    accountableExecutiveId: 'usr_ceo_1',
    accountableExecutiveName: 'Dawit Tadesse',
    accountableExecutiveTitle: 'Chief Executive Officer (CEO)',
    
    status: 'In Progress',
    progress: 55,
    currentStage: 'Director Operational Execution & Policy Recalibration',
    daysRemaining: 59,
    isOverdue: false,
    lastAction: 'Director accepted ownership and initiated portfolio stress-testing model update',
    lastActionDate: '2026-08-04T11:20:00Z',
    lastActionUserId: 'usr_dir_compliance',
    lastActionUserName: 'Daniel Kebede',
    nextRequiredAction: 'Director to complete exposure recalculations and submit implementation report with model audit',
    nextActionRole: 'DIRECTOR',
    overallStatus: 'Operational Execution on Track',
    
    documents: [
      {
        id: 'doc_201',
        name: 'Board_Resolution_031_Exposure_Limits.pdf',
        category: 'RESOLUTION',
        fileType: 'application/pdf',
        fileSize: '3.2 MB',
        uploadedBy: 'Rahel Solomon',
        uploadedByRole: 'BOARD_SECRETARIAT',
        uploadedAt: '2026-07-30T10:00:00Z',
      },
    ],
    
    routingPath: [
      {
        id: 'wn_201',
        level: 'BOARD_SECRETARIAT',
        label: 'Board Secretariat',
        userId: 'usr_sec_1',
        userName: 'Rahel Solomon',
        userTitle: 'Head of Board Secretariat & Corporate Governance',
        role: 'BOARD_SECRETARIAT',
        businessArea: 'Board Secretariat',
        assignedAt: '2026-07-30T10:00:00Z',
        actedAt: '2026-07-30T11:00:00Z',
        actionTaken: 'Registered Resolution and transmitted to CEO',
        status: 'COMPLETED',
      },
      {
        id: 'wn_202',
        level: 'CEO',
        label: 'Chief Executive Officer',
        userId: 'usr_ceo_1',
        userName: 'Dawit Tadesse',
        userTitle: 'Chief Executive Officer (CEO)',
        role: 'CEO',
        businessArea: 'Executive Management',
        assignedAt: '2026-07-30T11:00:00Z',
        actedAt: '2026-08-01T15:20:00Z',
        actionTaken: 'Assigned to Chief Risk & Compliance Officer',
        status: 'COMPLETED',
        comment: 'Please enforce strict compliance across Corporate and Commercial loan books.',
      },
      {
        id: 'wn_203',
        level: 'CHIEF',
        label: 'Chief Risk Officer',
        userId: 'usr_chief_risk',
        userName: 'Michael Girma',
        userTitle: 'Chief Risk & Compliance Officer (CRO)',
        role: 'CHIEF',
        businessArea: 'Risk & Compliance',
        assignedAt: '2026-08-01T15:20:00Z',
        actedAt: '2026-08-02T10:15:00Z',
        actionTaken: 'Assigned directly to Director - Compliance (flexible route, skipping Deputy Chief)',
        status: 'COMPLETED',
        comment: 'Daniel, lead the model revision and update system hard stops.',
      },
      {
        id: 'wn_204',
        level: 'DIRECTOR',
        label: 'Director - Compliance',
        userId: 'usr_dir_compliance',
        userName: 'Daniel Kebede',
        userTitle: 'Director - Regulatory Compliance & AML/CFT',
        role: 'DIRECTOR',
        businessArea: 'Risk & Compliance',
        assignedAt: '2026-08-02T10:15:00Z',
        actedAt: '2026-08-04T11:20:00Z',
        actionTaken: 'Accepted Ownership and initialized risk matrix adjustments',
        status: 'ACTIVE',
      },
    ],
    
    clarifications: [],
    createdAt: '2026-07-30T10:00:00Z',
    createdBy: 'usr_sec_1',
    createdByName: 'Rahel Solomon',
    updatedAt: '2026-08-04T11:20:00Z',
  },
  {
    id: 'BOD-2026-003',
    resolutionNumber: 'NIB/BOD/POL/2026/012',
    matterType: 'Policy / Rule',
    title: 'Mandatory Multi-Factor Authentication (MFA) & Biometric Authorization for High-Value Corporate Transfers',
    description:
      'Approval of amended Cyber Security & Electronic Funds Transfer Policy requiring hardware token / biometric MFA for corporate internet banking transfers exceeding ETB 5,000,000.',
    boardMeetingDate: '2026-05-20',
    boardDecisionDate: '2026-05-21',
    effectiveDate: '2026-06-01',
    priority: 'Urgent',
    deadline: '2026-08-01',
    businessArea: 'Information Technology',
    
    responsibleChiefId: 'usr_chief_it',
    responsibleChiefName: 'Henok Samuel',
    responsibleChiefTitle: 'Chief Information & Digital Officer (CIDO)',
    
    responsibleDeputyChiefId: 'usr_deputy_digital',
    responsibleDeputyChiefName: 'Samrawit Negash',
    responsibleDeputyChiefTitle: 'Deputy Chief - Digital Channels & Payments',
    
    responsibleDirectorId: 'usr_dir_it_sec',
    responsibleDirectorName: 'Meron Tesfaye',
    responsibleDirectorTitle: 'Director - IT Infrastructure & Cyber Security',
    
    currentOwnerId: 'usr_sec_1',
    currentOwnerName: 'Rahel Solomon',
    currentOwnerRole: 'BOARD_SECRETARIAT',
    currentOwnerTitle: 'Head of Board Secretariat & Corporate Governance',
    
    accountableExecutiveId: 'usr_ceo_1',
    accountableExecutiveName: 'Dawit Tadesse',
    accountableExecutiveTitle: 'Chief Executive Officer (CEO)',
    
    status: 'Closed',
    progress: 100,
    currentStage: 'Formally Closed by Board Secretariat & Archival Completed',
    daysRemaining: 0,
    isOverdue: false,
    lastAction: 'Board Secretariat completed final closure and recorded verification in Board Minutes',
    lastActionDate: '2026-08-05T16:00:00Z',
    lastActionUserId: 'usr_sec_1',
    lastActionUserName: 'Rahel Solomon',
    nextRequiredAction: 'None (Matter Formally Closed)',
    nextActionRole: 'BOARD_SECRETARIAT',
    overallStatus: 'Successfully Implemented & Formally Closed',
    
    documents: [
      {
        id: 'doc_301',
        name: 'Policy_Approval_BOD_Pol_2026_012.pdf',
        category: 'ORIGINAL_BOARD_DOC',
        fileType: 'application/pdf',
        fileSize: '5.2 MB',
        uploadedBy: 'Rahel Solomon',
        uploadedByRole: 'BOARD_SECRETARIAT',
        uploadedAt: '2026-05-22T08:30:00Z',
      },
      {
        id: 'doc_302',
        name: 'Penetration_Test_and_MFA_Validation_Cert.pdf',
        category: 'IMPLEMENTATION_EVIDENCE',
        fileType: 'application/pdf',
        fileSize: '3.6 MB',
        uploadedBy: 'Meron Tesfaye',
        uploadedByRole: 'DIRECTOR',
        uploadedAt: '2026-07-25T11:00:00Z',
      },
      {
        id: 'doc_303',
        name: 'Executive_Closure_Confirmation_Memo.pdf',
        category: 'COMPLETION_REPORT',
        fileType: 'application/pdf',
        fileSize: '1.1 MB',
        uploadedBy: 'Dawit Tadesse',
        uploadedByRole: 'CEO',
        uploadedAt: '2026-08-03T17:00:00Z',
      },
    ],
    
    implementationReport: {
      id: 'rep_003',
      submittedBy: 'usr_dir_it_sec',
      directorName: 'Meron Tesfaye',
      directorTitle: 'Director - IT Infrastructure & Cyber Security',
      submissionDate: '2026-07-25',
      actionTaken: 'Integrated FIDO2 & TOTP hardware authentication into Corporate Internet Banking gateway. Configured system hard enforcement on transactions > ETB 5M.',
      whatWasImplemented: '1. Deployed Dual-Authorization & Hardware OTP authentication module.\n2. Onboarded top 450 corporate banking clients.\n3. Third-party vulnerability assessment & audit clearance completed.',
      implementationDate: '2026-07-20',
      responsibleArea: 'IT Security Directorate in partnership with E-Banking Unit',
      resultOutcome: 'Zero unauthorized corporate transfer incidents recorded since deployment. 100% corporate client compliance achieved.',
      currentCondition: 'Active and monitored 24/7 via Security Operations Center (SOC).',
      remainingIssues: 'None',
      evidenceDocuments: [],
      comments: 'All policy technical and operational parameters fully met.',
      completionDate: '2026-07-25',
      completionStatus: 'Completed',
      reviewedBy: 'Henok Samuel',
      reviewerRole: 'CHIEF',
      reviewerTitle: 'Chief Information & Digital Officer (CIDO)',
      reviewDate: '2026-07-29',
      reviewNotes: 'Reviewed technical implementation and pentest audit results. Exceeds standard requirements. Recommended for executive sign-off.',
      reviewDecision: 'Approved',
    },
    
    routingPath: [
      {
        id: 'wn_301',
        level: 'BOARD_SECRETARIAT',
        label: 'Board Secretariat',
        userId: 'usr_sec_1',
        userName: 'Rahel Solomon',
        userTitle: 'Head of Board Secretariat & Corporate Governance',
        role: 'BOARD_SECRETARIAT',
        businessArea: 'Board Secretariat',
        assignedAt: '2026-05-22T08:30:00Z',
        actedAt: '2026-05-22T09:00:00Z',
        actionTaken: 'Registered policy decision and routed to CEO',
        status: 'COMPLETED',
      },
      {
        id: 'wn_302',
        level: 'CEO',
        label: 'Chief Executive Officer',
        userId: 'usr_ceo_1',
        userName: 'Dawit Tadesse',
        userTitle: 'Chief Executive Officer (CEO)',
        role: 'CEO',
        businessArea: 'Executive Management',
        assignedAt: '2026-05-22T09:00:00Z',
        actedAt: '2026-05-23T11:00:00Z',
        actionTaken: 'Forwarded to Chief Information & Digital Officer',
        status: 'COMPLETED',
      },
      {
        id: 'wn_303',
        level: 'CHIEF',
        label: 'Chief Information Officer',
        userId: 'usr_chief_it',
        userName: 'Henok Samuel',
        userTitle: 'Chief Information & Digital Officer (CIDO)',
        role: 'CHIEF',
        businessArea: 'Information Technology',
        assignedAt: '2026-05-23T11:00:00Z',
        actedAt: '2026-05-24T14:30:00Z',
        actionTaken: 'Assigned to Deputy Chief Samrawit Negash',
        status: 'COMPLETED',
      },
      {
        id: 'wn_304',
        level: 'DEPUTY_CHIEF',
        label: 'Deputy Chief - Digital Channels',
        userId: 'usr_deputy_digital',
        userName: 'Samrawit Negash',
        userTitle: 'Deputy Chief - Digital Channels & Payments',
        role: 'DEPUTY_CHIEF',
        businessArea: 'Information Technology',
        assignedAt: '2026-05-24T14:30:00Z',
        actedAt: '2026-05-25T10:00:00Z',
        actionTaken: 'Assigned to Director Meron Tesfaye as Operational Owner',
        status: 'COMPLETED',
      },
      {
        id: 'wn_305',
        level: 'DIRECTOR',
        label: 'Director - IT Security',
        userId: 'usr_dir_it_sec',
        userName: 'Meron Tesfaye',
        userTitle: 'Director - IT Infrastructure & Cyber Security',
        role: 'DIRECTOR',
        businessArea: 'Information Technology',
        assignedAt: '2026-05-25T10:00:00Z',
        actedAt: '2026-07-25T11:00:00Z',
        actionTaken: 'Completed system development, penetration testing, and submitted final report',
        status: 'COMPLETED',
      },
      {
        id: 'wn_306',
        level: 'REVIEW_CONFIRMATION',
        label: 'Review & Confirmation',
        userId: 'usr_ceo_1',
        userName: 'Dawit Tadesse',
        userTitle: 'Chief Executive Officer (CEO)',
        role: 'CEO',
        businessArea: 'Executive Management',
        assignedAt: '2026-07-29T10:00:00Z',
        actedAt: '2026-08-03T17:00:00Z',
        actionTaken: 'Reviewed and confirmed successful operational completion',
        status: 'COMPLETED',
      },
      {
        id: 'wn_307',
        level: 'CLOSED',
        label: 'Closed',
        userId: 'usr_sec_1',
        userName: 'Rahel Solomon',
        userTitle: 'Head of Board Secretariat & Corporate Governance',
        role: 'BOARD_SECRETARIAT',
        businessArea: 'Board Secretariat',
        assignedAt: '2026-08-03T17:00:00Z',
        actedAt: '2026-08-05T16:00:00Z',
        actionTaken: 'Formally closed and cataloged in official Board archives',
        status: 'COMPLETED',
      },
    ],
    
    clarifications: [],
    createdAt: '2026-05-22T08:30:00Z',
    createdBy: 'usr_sec_1',
    createdByName: 'Rahel Solomon',
    updatedAt: '2026-08-05T16:00:00Z',
    closedAt: '2026-08-05T16:00:00Z',
    closedBy: 'usr_sec_1',
    closedByName: 'Rahel Solomon',
  },
  {
    id: 'BOD-2026-004',
    resolutionNumber: 'NIB/BOD/INST/2026/018',
    matterType: 'Instruction',
    title: 'Audit Rectification on Forex Allocation & Letter of Credit Verification Controls',
    description:
      'Instruction from the Board Audit Committee to immediately introduce dual-signature validation protocols and anti-duplicate bill of lading screening for all import Letters of Credit exceeding USD 100,000 equivalent.',
    boardMeetingDate: '2026-08-02',
    boardDecisionDate: '2026-08-03',
    effectiveDate: '2026-08-10',
    priority: 'Urgent',
    deadline: '2026-08-25',
    businessArea: 'Banking Operations',
    
    responsibleChiefId: 'usr_chief_ops',
    responsibleChiefName: 'Ephrem Bekele',
    responsibleChiefTitle: 'Chief Operations Officer (COO)',
    
    responsibleDirectorId: 'usr_dir_branch_ops',
    responsibleDirectorName: 'Solomon Mengistu',
    responsibleDirectorTitle: 'Director - Branch Operations & Service Delivery',
    
    currentOwnerId: 'usr_chief_ops',
    currentOwnerName: 'Ephrem Bekele',
    currentOwnerRole: 'CHIEF',
    currentOwnerTitle: 'Chief Operations Officer (COO)',
    
    accountableExecutiveId: 'usr_ceo_1',
    accountableExecutiveName: 'Dawit Tadesse',
    accountableExecutiveTitle: 'Chief Executive Officer (CEO)',
    
    status: 'Clarification Required',
    progress: 30,
    currentStage: 'Clarification Requested by Director on Trade Finance Division Jurisdiction',
    daysRemaining: 8,
    isOverdue: false,
    lastAction: 'Director requested clarification regarding whether centralized International Banking Division or Branch Operations holds primary execution authority',
    lastActionDate: '2026-08-14T09:15:00Z',
    lastActionUserId: 'usr_dir_branch_ops',
    lastActionUserName: 'Solomon Mengistu',
    nextRequiredAction: 'Chief Operations Officer / CEO to provide written clarification to Director',
    nextActionRole: 'CHIEF',
    overallStatus: 'Pending Clarification Response',
    
    documents: [
      {
        id: 'doc_401',
        name: 'Board_Audit_Committee_Instruction_LC_Controls.pdf',
        category: 'ORIGINAL_BOARD_DOC',
        fileType: 'application/pdf',
        fileSize: '1.9 MB',
        uploadedBy: 'Rahel Solomon',
        uploadedByRole: 'BOARD_SECRETARIAT',
        uploadedAt: '2026-08-04T09:00:00Z',
      },
    ],
    
    routingPath: [
      {
        id: 'wn_401',
        level: 'BOARD_SECRETARIAT',
        label: 'Board Secretariat',
        userId: 'usr_sec_1',
        userName: 'Rahel Solomon',
        userTitle: 'Head of Board Secretariat & Corporate Governance',
        role: 'BOARD_SECRETARIAT',
        businessArea: 'Board Secretariat',
        assignedAt: '2026-08-04T09:00:00Z',
        actedAt: '2026-08-04T10:00:00Z',
        actionTaken: 'Registered Instruction and forwarded to CEO',
        status: 'COMPLETED',
      },
      {
        id: 'wn_402',
        level: 'CEO',
        label: 'Chief Executive Officer',
        userId: 'usr_ceo_1',
        userName: 'Dawit Tadesse',
        userTitle: 'Chief Executive Officer (CEO)',
        role: 'CEO',
        businessArea: 'Executive Management',
        assignedAt: '2026-08-04T10:00:00Z',
        actedAt: '2026-08-06T11:30:00Z',
        actionTaken: 'Assigned to Chief Operations Officer Ephrem Bekele',
        status: 'COMPLETED',
      },
      {
        id: 'wn_403',
        level: 'CHIEF',
        label: 'Chief Operations Officer',
        userId: 'usr_chief_ops',
        userName: 'Ephrem Bekele',
        userTitle: 'Chief Operations Officer (COO)',
        role: 'CHIEF',
        businessArea: 'Banking Operations',
        assignedAt: '2026-08-06T11:30:00Z',
        actedAt: '2026-08-07T14:00:00Z',
        actionTaken: 'Assigned to Director Solomon Mengistu',
        status: 'ACTIVE',
      },
      {
        id: 'wn_404',
        level: 'DIRECTOR',
        label: 'Director - Branch Operations',
        userId: 'usr_dir_branch_ops',
        userName: 'Solomon Mengistu',
        userTitle: 'Director - Branch Operations & Service Delivery',
        role: 'DIRECTOR',
        businessArea: 'Banking Operations',
        assignedAt: '2026-08-07T14:00:00Z',
        actedAt: '2026-08-14T09:15:00Z',
        actionTaken: 'Requested Clarification regarding International Banking Department involvement',
        status: 'PENDING',
      },
    ],
    
    clarifications: [
      {
        id: 'clar_401',
        requestedBy: 'usr_dir_branch_ops',
        requesterName: 'Solomon Mengistu',
        requesterRole: 'DIRECTOR',
        requesterTitle: 'Director - Branch Operations & Service Delivery',
        requestedTo: 'usr_chief_ops',
        recipientName: 'Ephrem Bekele',
        recipientRole: 'CHIEF',
        requestedAt: '2026-08-14T09:15:00Z',
        question:
          'Does this instruction apply exclusively to Branch Forex counters or also to Head Office Trade Services / International Banking Directorate? Should we co-sign the new checklist with Director of International Banking?',
        status: 'OPEN',
      },
    ],
    createdAt: '2026-08-04T09:00:00Z',
    createdBy: 'usr_sec_1',
    createdByName: 'Rahel Solomon',
    updatedAt: '2026-08-14T09:15:00Z',
  },
  {
    id: 'BOD-2026-005',
    resolutionNumber: 'NIB/BOD/DEC/2026/088',
    matterType: 'Decision',
    title: 'Branch Network Expansion Strategy: Approval for 12 New Regional Hubs in Amhara, Oromia & Sidama',
    description:
      'The Board approved the establishment and capital expenditure allocation of ETB 280,000,000 for 12 new strategic branches, mandating completion of site acquisitions and leasehold negotiations by Q2 FY 2026/27.',
    boardMeetingDate: '2026-08-08',
    boardDecisionDate: '2026-08-09',
    effectiveDate: '2026-08-20',
    priority: 'Medium',
    deadline: '2026-11-30',
    businessArea: 'Retail Banking',
    
    responsibleChiefId: 'usr_chief_retail',
    responsibleChiefName: 'Bethlehem Haile',
    responsibleChiefTitle: 'Chief Retail & SME Banking Officer',
    
    responsibleDirectorId: 'usr_dir_branch_ops',
    responsibleDirectorName: 'Solomon Mengistu',
    responsibleDirectorTitle: 'Director - Branch Operations & Service Delivery',
    
    currentOwnerId: 'usr_chief_retail',
    currentOwnerName: 'Bethlehem Haile',
    currentOwnerRole: 'CHIEF',
    currentOwnerTitle: 'Chief Retail & SME Banking Officer',
    
    accountableExecutiveId: 'usr_ceo_1',
    accountableExecutiveName: 'Dawit Tadesse',
    accountableExecutiveTitle: 'Chief Executive Officer (CEO)',
    
    status: 'Assigned',
    progress: 15,
    currentStage: 'Assigned to Chief Retail Banking Officer for Operational Staging',
    daysRemaining: 105,
    isOverdue: false,
    lastAction: 'CEO assigned matter to Chief Retail Banking Officer with Capex budget parameters',
    lastActionDate: '2026-08-12T16:45:00Z',
    lastActionUserId: 'usr_ceo_1',
    lastActionUserName: 'Dawit Tadesse',
    nextRequiredAction: 'Chief Retail Banking Officer to accept ownership or assign to Director',
    nextActionRole: 'CHIEF',
    overallStatus: 'Routing & Planning Stage',
    
    documents: [
      {
        id: 'doc_501',
        name: 'BOD_Decision_088_Expansion_Signed.pdf',
        category: 'ORIGINAL_BOARD_DOC',
        fileType: 'application/pdf',
        fileSize: '4.8 MB',
        uploadedBy: 'Rahel Solomon',
        uploadedByRole: 'BOARD_SECRETARIAT',
        uploadedAt: '2026-08-10T14:00:00Z',
      },
    ],
    
    routingPath: [
      {
        id: 'wn_501',
        level: 'BOARD_SECRETARIAT',
        label: 'Board Secretariat',
        userId: 'usr_sec_1',
        userName: 'Rahel Solomon',
        userTitle: 'Head of Board Secretariat & Corporate Governance',
        role: 'BOARD_SECRETARIAT',
        businessArea: 'Board Secretariat',
        assignedAt: '2026-08-10T14:00:00Z',
        actedAt: '2026-08-10T15:30:00Z',
        actionTaken: 'Registered Decision and transmitted to CEO',
        status: 'COMPLETED',
      },
      {
        id: 'wn_502',
        level: 'CEO',
        label: 'Chief Executive Officer',
        userId: 'usr_ceo_1',
        userName: 'Dawit Tadesse',
        userTitle: 'Chief Executive Officer (CEO)',
        role: 'CEO',
        businessArea: 'Executive Management',
        assignedAt: '2026-08-10T15:30:00Z',
        actedAt: '2026-08-12T16:45:00Z',
        actionTaken: 'Assigned to Chief Retail & SME Banking Officer',
        status: 'COMPLETED',
        comment: 'Ensure regional parity and proximity to key commercial coffee and grain trade corridors.',
      },
      {
        id: 'wn_503',
        level: 'CHIEF',
        label: 'Chief Retail Banking Officer',
        userId: 'usr_chief_retail',
        userName: 'Bethlehem Haile',
        userTitle: 'Chief Retail & SME Banking Officer',
        role: 'CHIEF',
        businessArea: 'Retail Banking',
        assignedAt: '2026-08-12T16:45:00Z',
        status: 'ACTIVE',
      },
    ],
    
    clarifications: [],
    createdAt: '2026-08-10T14:00:00Z',
    createdBy: 'usr_sec_1',
    createdByName: 'Rahel Solomon',
    updatedAt: '2026-08-12T16:45:00Z',
  },
  {
    id: 'BOD-2026-006',
    resolutionNumber: 'NIB/BOD/DIR/2026/049',
    matterType: 'Other Board Direction',
    title: 'Disaster Recovery (DR) Full Switchover Simulation & Business Continuity Audit',
    description:
      'The Board mandated that executive management conduct an unannounced live core banking switchover to the Debre Zeit secondary data center over a weekend, with mandatory third-party audit verification.',
    boardMeetingDate: '2026-08-14',
    boardDecisionDate: '2026-08-14',
    effectiveDate: '2026-08-25',
    priority: 'High',
    deadline: '2026-09-15',
    businessArea: 'Information Technology',
    
    responsibleDirectorId: 'usr_dir_it_sec',
    responsibleDirectorName: 'Meron Tesfaye',
    responsibleDirectorTitle: 'Director - IT Infrastructure & Cyber Security',
    
    currentOwnerId: 'usr_ceo_1',
    currentOwnerName: 'Dawit Tadesse',
    currentOwnerRole: 'CEO',
    currentOwnerTitle: 'Chief Executive Officer (CEO)',
    
    accountableExecutiveId: 'usr_ceo_1',
    accountableExecutiveName: 'Dawit Tadesse',
    accountableExecutiveTitle: 'Chief Executive Officer (CEO)',
    
    status: 'Under Review',
    progress: 5,
    currentStage: 'Under Initial Review by CEO for Resource & Scheduling Allocation',
    daysRemaining: 29,
    isOverdue: false,
    lastAction: 'Board Secretariat registered direction and transmitted to CEO',
    lastActionDate: '2026-08-16T11:00:00Z',
    lastActionUserId: 'usr_sec_1',
    lastActionUserName: 'Rahel Solomon',
    nextRequiredAction: 'CEO to review and assign to Chief Information Officer',
    nextActionRole: 'CEO',
    overallStatus: 'Awaiting Executive Assignment',
    
    documents: [
      {
        id: 'doc_601',
        name: 'BOD_Direction_DR_Testing_Mandate.pdf',
        category: 'ORIGINAL_BOARD_DOC',
        fileType: 'application/pdf',
        fileSize: '2.1 MB',
        uploadedBy: 'Rahel Solomon',
        uploadedByRole: 'BOARD_SECRETARIAT',
        uploadedAt: '2026-08-16T11:00:00Z',
      },
    ],
    
    routingPath: [
      {
        id: 'wn_601',
        level: 'BOARD_SECRETARIAT',
        label: 'Board Secretariat',
        userId: 'usr_sec_1',
        userName: 'Rahel Solomon',
        userTitle: 'Head of Board Secretariat & Corporate Governance',
        role: 'BOARD_SECRETARIAT',
        businessArea: 'Board Secretariat',
        assignedAt: '2026-08-16T11:00:00Z',
        actedAt: '2026-08-16T11:00:00Z',
        actionTaken: 'Registered Board Direction and forwarded to CEO',
        status: 'COMPLETED',
      },
      {
        id: 'wn_602',
        level: 'CEO',
        label: 'Chief Executive Officer',
        userId: 'usr_ceo_1',
        userName: 'Dawit Tadesse',
        userTitle: 'Chief Executive Officer (CEO)',
        role: 'CEO',
        businessArea: 'Executive Management',
        assignedAt: '2026-08-16T11:00:00Z',
        status: 'ACTIVE',
      },
    ],
    
    clarifications: [],
    createdAt: '2026-08-16T11:00:00Z',
    createdBy: 'usr_sec_1',
    createdByName: 'Rahel Solomon',
    updatedAt: '2026-08-16T11:00:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log_001',
    matterId: 'BOD-2026-001',
    timestamp: '2026-07-17T09:00:00Z',
    userId: 'usr_sec_1',
    userName: 'Rahel Solomon',
    userRole: 'BOARD_SECRETARIAT',
    userTitle: 'Head of Board Secretariat & Corporate Governance',
    action: 'Matter Created',
    newStatus: 'Received',
    comment: 'BOD Directive registered from 42nd Regular Board Meeting (Resolution NIB/BOD/DIR/2026/025)',
    supportingDocName: 'BOD_Resolution_2026_025_Signed.pdf',
  },
  {
    id: 'log_002',
    matterId: 'BOD-2026-001',
    timestamp: '2026-07-17T10:15:00Z',
    userId: 'usr_sec_1',
    userName: 'Rahel Solomon',
    userRole: 'BOARD_SECRETARIAT',
    userTitle: 'Head of Board Secretariat & Corporate Governance',
    action: 'Matter Forwarded',
    previousOwner: {
      id: 'usr_sec_1',
      name: 'Rahel Solomon',
      role: 'BOARD_SECRETARIAT',
      title: 'Head of Board Secretariat & Corporate Governance',
    },
    newOwner: {
      id: 'usr_ceo_1',
      name: 'Dawit Tadesse',
      role: 'CEO',
      title: 'Chief Executive Officer (CEO)',
    },
    previousStatus: 'Received',
    newStatus: 'Under Review',
    comment: 'Transmitted to CEO Secretariat for executive review and operational assignment',
  },
  {
    id: 'log_003',
    matterId: 'BOD-2026-001',
    timestamp: '2026-07-18T08:45:00Z',
    userId: 'usr_ceo_1',
    userName: 'Dawit Tadesse',
    userRole: 'CEO',
    userTitle: 'Chief Executive Officer (CEO)',
    action: 'Matter Assigned',
    previousOwner: {
      id: 'usr_ceo_1',
      name: 'Dawit Tadesse',
      role: 'CEO',
      title: 'Chief Executive Officer (CEO)',
    },
    newOwner: {
      id: 'usr_chief_ops',
      name: 'Ephrem Bekele',
      role: 'CHIEF',
      title: 'Chief Operations Officer (COO)',
    },
    previousStatus: 'Under Review',
    newStatus: 'Assigned',
    comment: 'Assigned to Chief Operations Officer. Lead operational delivery.',
  },
  {
    id: 'log_004',
    matterId: 'BOD-2026-001',
    timestamp: '2026-07-18T14:00:00Z',
    userId: 'usr_chief_ops',
    userName: 'Ephrem Bekele',
    userRole: 'CHIEF',
    userTitle: 'Chief Operations Officer (COO)',
    action: 'Matter Forwarded',
    previousOwner: {
      id: 'usr_chief_ops',
      name: 'Ephrem Bekele',
      role: 'CHIEF',
      title: 'Chief Operations Officer (COO)',
    },
    newOwner: {
      id: 'usr_deputy_branch',
      name: 'Yonas Alemu',
      role: 'DEPUTY_CHIEF',
      title: 'Deputy Chief - Branch Network Operations',
    },
    previousStatus: 'Assigned',
    newStatus: 'Assigned',
    comment: 'Forwarded to Deputy Chief Yonas Alemu for branch coordination.',
  },
  {
    id: 'log_005',
    matterId: 'BOD-2026-001',
    timestamp: '2026-07-19T09:30:00Z',
    userId: 'usr_deputy_branch',
    userName: 'Yonas Alemu',
    userRole: 'DEPUTY_CHIEF',
    userTitle: 'Deputy Chief - Branch Network Operations',
    action: 'Matter Assigned',
    previousOwner: {
      id: 'usr_deputy_branch',
      name: 'Yonas Alemu',
      role: 'DEPUTY_CHIEF',
      title: 'Deputy Chief - Branch Network Operations',
    },
    newOwner: {
      id: 'usr_dir_branch_ops',
      name: 'Solomon Mengistu',
      role: 'DIRECTOR',
      title: 'Director - Branch Operations & Service Delivery',
    },
    previousStatus: 'Assigned',
    newStatus: 'Assigned',
    comment: 'Assigned to Director Solomon Mengistu as Final Operational Owner.',
  },
  {
    id: 'log_006',
    matterId: 'BOD-2026-001',
    timestamp: '2026-07-19T11:00:00Z',
    userId: 'usr_dir_branch_ops',
    userName: 'Solomon Mengistu',
    userRole: 'DIRECTOR',
    userTitle: 'Director - Branch Operations & Service Delivery',
    action: 'Matter Accepted',
    previousStatus: 'Assigned',
    newStatus: 'In Progress',
    comment: 'Director Solomon Mengistu confirmed acceptance of operational ownership. Commenced SOP restructuring and training design.',
  },
  {
    id: 'log_007',
    matterId: 'BOD-2026-001',
    timestamp: '2026-08-15T14:30:00Z',
    userId: 'usr_dir_branch_ops',
    userName: 'Solomon Mengistu',
    userRole: 'DIRECTOR',
    userTitle: 'Director - Branch Operations & Service Delivery',
    action: 'Implementation Submitted',
    previousOwner: {
      id: 'usr_dir_branch_ops',
      name: 'Solomon Mengistu',
      role: 'DIRECTOR',
      title: 'Director - Branch Operations & Service Delivery',
    },
    newOwner: {
      id: 'usr_chief_ops',
      name: 'Ephrem Bekele',
      role: 'CHIEF',
      title: 'Chief Operations Officer (COO)',
    },
    previousStatus: 'In Progress',
    newStatus: 'Implementation Submitted',
    comment: 'Final Implementation Report and verified training logs submitted for executive confirmation.',
    supportingDocName: 'Branch_Staff_Training_Attendance_Log_All_Regions.xlsx',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_1',
    userId: 'usr_chief_ops',
    matterId: 'BOD-2026-001',
    matterTitle: 'Implementation of New Branch Customer Complaint Procedure & 48-Hour Resolution Framework',
    title: 'Implementation Report Submitted',
    message: 'Director Solomon Mengistu has submitted the final Implementation Report with verified training logs for BOD-2026-001.',
    type: 'IMPLEMENTATION_SUBMITTED',
    timestamp: '2026-08-15T14:30:00Z',
    isRead: false,
  },
  {
    id: 'notif_2',
    userId: 'usr_chief_ops',
    matterId: 'BOD-2026-004',
    matterTitle: 'Audit Rectification on Forex Allocation & Letter of Credit Verification Controls',
    title: 'Clarification Requested',
    message: 'Director Solomon Mengistu requested clarification on trade finance jurisdiction for BOD-2026-004.',
    type: 'CLARIFICATION',
    timestamp: '2026-08-14T09:15:00Z',
    isRead: false,
  },
  {
    id: 'notif_3',
    userId: 'usr_dir_compliance',
    matterId: 'BOD-2026-002',
    matterTitle: 'Capital Adequacy & Single Obligor Exposure Limits Enhancement for FY 2026/27',
    title: 'New Matter Assigned to You',
    message: 'Chief Risk Officer Michael Girma assigned BOD-2026-002 to you as Operational Owner.',
    type: 'ASSIGNMENT',
    timestamp: '2026-08-02T10:15:00Z',
    isRead: true,
  },
  {
    id: 'notif_4',
    userId: 'usr_ceo_1',
    matterId: 'BOD-2026-006',
    matterTitle: 'Disaster Recovery (DR) Full Switchover Simulation & Business Continuity Audit',
    title: 'New BOD Matter Received',
    message: 'Board Secretariat transmitted BOD-2026-006 (Other Board Direction) for executive review.',
    type: 'FORWARD',
    timestamp: '2026-08-16T11:00:00Z',
    isRead: false,
  },
];
